# Generated by Django 2.0 on 2017-12-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('source_hint', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('issue', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['title', 'issue'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.RecipeSource'),
        ),
    ]
