# Generated by Django 2.0 on 2017-12-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('num_entries_per_day', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_entry', models.PositiveSmallIntegerField()),
                ('text', models.CharField(blank=True, max_length=250)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Calendar')),
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'ordering': ['date', 'num_entry'],
            },
        ),
    ]
